title: ""
author: "Eduardo Napierala"
description: ""
permalink: /:title/
lang: "es"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "/", icon: "home", title: "Inicio"}
  - {title: "Trajes", url: "/trajes/", icon: "nut"} # Un icono geométrico que recuerda a un botón
  - {title: "Camisas", url: "/camisas/", icon: "tag"} # Icono de etiqueta de calidad
  - {title: "Sacos", url: "/sacos/", icon: "tag"} # Icono de etiqueta de calidad
  - {title: "Chalecos", url: "/chalecos/", icon: "tag"} # Icono de etiqueta de calidad
  - {title: "Pantalones", url: "/pantalon/", icon: "list"} # Icono de etiqueta de calidad
  - {title: "Base niños", url: "/base-ninos/", icon: "list"} # Icono de etiqueta de calidad
  - {title: "Guías", url: "/guias/", icon: "list"} # Icono de etiqueta de calidad

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: WhatsApp, icon: whatsapp, url: "https://wa.me/58412-3133803"}
  - {title: Instagram, icon: instagram, url: "https://instagram.com/tiendasrori"}
  #  - {title: Mail, icon: envelope, url: "mailto:tu_correo@ejemplo.com"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

collections:
  trajes:
    output: true
    permalink: /trajes/:path/
  camisas:
    output: true
    permalink: /camisas/:path/
  sacos:
    output: true
    permalink: /sacos/:path/
  chalecos:
    output: true
    permalink: /chalecos/:path/
  pantalon:
    output: true
    permalink: /pantalon/:path/
  base_nino:
    output: true
    permalink: /base-ninos/:path/
  guias_visuales:      # <--- Nueva colección
    output: true
    permalink: /guias/:path/
