title: "RORI"
author: "Eduardo Napierala"
description: "Trajes a la medida RORI"
permalink: /:title/
lang: "es"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {title: "Trajes", url: "/trajes/"}
  - {title: "Camisas", url: "/camisas/"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: WhatsApp, icon: whatsapp, url: "https://wa.me/58412-3133803"}
  - {title: Instagram, icon: instagram, url: "https://instagram.com/tiendasrori"}
  #  - {title: Mail, icon: envelope, url: "mailto:tu_correo@ejemplo.com"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

collections:
  trajes:
    output: true
    permalink: /trajes/:path/
  camisas:
    output: true
    permalink: /camisas/:path/
